### ISSUE TITLE
Crash on Startup [2021-11-03 Patch]

### ISSUE THREAD

**Issue by chartinger** [Didstopia/satisfactory-server#3]
As of 2021-11-03 a new parameter `MultiHome` seems to be required, otherwise the server will crash on startup.
(at least if it is run in an ipv4 docker, i did not check with ipv6 support)

See
* https://questions.satisfactorygame.com/post/61830560831c852052359b1c
* https://satisfactory.fandom.com/wiki/Dedicated_servers#Post-Update_Note_.5B2021-11-03.5D

https://github.com/Didstopia/satisfactory-server/blob/7697e38e11ae302a1bceed5f78f2703887505aa9/Dockerfile#L38

should now be

`ENV SATISFACTORY_SERVER_STARTUP_ARGUMENTS "FactoryGame -log -NoSteamClient -unattended -MultiHome=0.0.0.0" `

(As a Workaround, the ENV var can be overridden on startup)

**Comment by Dids** [comment]
Thank you! Just noticed the same and came to the same conclusion when testing locally (0.0.0.0 binds to all available IPv4 addresses, skipping IPv6), but was pleasantly surprised to see that you'd reported the same exact issue _and_ workaround!

Releasing updated images and documentation in just a bit.
